### ISSUE TITLE
Integration available?

### ISSUE THREAD

**Issue by LukasK13** [idstein/esphome-optolink#1]
Hi,
I'm very interested in you optolink implementation for esphome. Do you already have a working version? I would love to use optolink with esphome.
Thank you

**Comment by idstein** [comment]
Hi,

It is working to successfully listen to the VitoConnect data exchange. I‘m currently working on having custom sensors defined to publish and interpret the read data from the KW300 protocol.

Stay tuned. It is likely only a few days away to get public.

**Comment by LukasK13** [comment]
Awesome, thank you very much.

**Comment by idstein** [comment]
Pushed the first implementation. This is currently based on having a VitoConnect triggering the calls. Plan is to first add write control (e.g. request hot water) and RPC (mainly because that is required to read aggregated energy information).

Finally, plan is to add some trivial polling mechanism.
